[project]
name = "storcard"
version = "0.2.1.0"
description = "Your own server for storing discount cards"
authors = [
    {name = "foxer928"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.3.0",
    "fastapi>=0.116.1",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",  
    "pyjwt>=2.10.1",
    "python-multipart>=0.0.20",
    "sqlalchemy>=2.0.43",
    "uvicorn[standard]>=0.35.0",
    "cryptography>=46.0.4",
]
[project.urls]
repository = "https://github.com/FoXeR928/StorCard"

[project.scripts]
app = "main:start_app"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
    "pytest-timeout>=2.4.0",
]

[tool.pytest.ini_options]
pythonpath = ["./src/"]
testpaths = ["tests"]

[tool.black]
target-version = ['py312']
